package app.randomuser.tabsquare.vo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import app.randomuser.tabsquare.vo.db.UserDetailData;
import app.randomuser.tabsquare.vo.db.UsersData;

import app.randomuser.tabsquare.vo.db.UserDetailDataDao;
import app.randomuser.tabsquare.vo.db.UsersDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDetailDataDaoConfig;
    private final DaoConfig usersDataDaoConfig;

    private final UserDetailDataDao userDetailDataDao;
    private final UsersDataDao usersDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDetailDataDaoConfig = daoConfigMap.get(UserDetailDataDao.class).clone();
        userDetailDataDaoConfig.initIdentityScope(type);

        usersDataDaoConfig = daoConfigMap.get(UsersDataDao.class).clone();
        usersDataDaoConfig.initIdentityScope(type);

        userDetailDataDao = new UserDetailDataDao(userDetailDataDaoConfig, this);
        usersDataDao = new UsersDataDao(usersDataDaoConfig, this);

        registerDao(UserDetailData.class, userDetailDataDao);
        registerDao(UsersData.class, usersDataDao);
    }
    
    public void clear() {
        userDetailDataDaoConfig.clearIdentityScope();
        usersDataDaoConfig.clearIdentityScope();
    }

    public UserDetailDataDao getUserDetailDataDao() {
        return userDetailDataDao;
    }

    public UsersDataDao getUsersDataDao() {
        return usersDataDao;
    }

}
